[package]
name = "pallet-succinct"
version = "1.0.0"
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# Substrate
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }
frame-support = { version = "4.0.0-dev", default-features = false }
frame-system = { version = "4.0.0-dev", default-features = false, path = "../system" }
sp-io = { version = "23.0.0", default-features = false }
sp-runtime = { version = "24.0.0", default-features = false }
sp-std = { version = "8.0.0", default-features = false }
sp-core = { version = "21.0.0", default-features = false }

bls12_381 = "0.7.0"
ark-bn254 = { version = "0.4.0", default-features = false, features = ["curve"] }
#sp-bls12-381 = { git = "https://github.com/paritytech/sp-curves.git", features = ["curve"], default-features = false }
ark-bls12-381 = { version = "0.4.0", features = ["curve"], default-features = false }

ark-groth16 = { version = "0.4.0", default-features = false }
ark-ec = "0.4.2"
ark-std = { version = "0.4.0", default-features = false }
ark-serialize = { version = "0.4.0", features = ["derive"], default-features = false }
ark-ff = { version = "0.4.0", default-features = false }
ark-snark = "0.4.0"
pairing = "0.22.0"
group = "0.12.1"
serde = { version = "1.0.149", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1.0.89", default-features = false, features = ["alloc"] }
uint = { version = "0.8", default-features = false }
sha2 = { version = "0.10.8", default-features = false }

frame-benchmarking = { version = "4.0.0-dev", default-features = false, optional = true }
log = "0.4.20"
hex-literal = { version = "0.3.4", optional = true }

[dev-dependencies]
sp-core = { version = "21.0.0", default-features = false }
hex-literal = "0.4.1"


[features]
default = ["std"]
std = [
    "codec/std",
    "frame-benchmarking?/std",
    "frame-support/std",
    "frame-system/std",
    "scale-info/std",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-std/std",
]
runtime-benchmarks = [
    "frame-benchmarking",
    "frame-benchmarking/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "sp-runtime/runtime-benchmarks",
    "hex-literal",
]
try-runtime = [
    "frame-support/try-runtime",
    "frame-system/try-runtime",
    "sp-runtime/try-runtime",
]
