[package]
name = "kate-rpc"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sp-api = { version = "4.0.0-dev" }
sp-std = { version = "5.0.0" }
frame-system = { version = "4.0.0-dev" }
frame-support = { version = "4.0.0-dev" }
kate-rpc-runtime-api = { path = "../kate-rpc-runtime-api" }
sc-client-db = { version = "0.10.0-dev" }
thiserror = "1.0.30" 
rs_merkle = { version = "1.2.0", default-features = false }
moka = "0.10"

codec = { package = "parity-scale-codec", version = "3" }
da-primitives = { version = "0.4" }
kate = { version = "0.6" }
kate-recovery = { version = "0.8" }
jsonrpsee = { version = "0.16.2", features = ["server", "client", "macros"] }

frame-system-rpc-runtime-api = "4.0.0-dev"
sc-client-api = "4.0.0-dev"
sp-blockchain = "4.0.0-dev"
sp-rpc = "6.0.0"
sp-runtime = "7.0.0"
sp-core = "7.0.0"
