[package]
name = "kate-rpc"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
avail-base = { path = "../../base" }
da-runtime = { path = "../../runtime" }
da-control = { path = "../../pallets/dactr" }
pallet-vector = { path = "../../pallets/vector" }

avail-core = { workspace = true, default-features = false }
kate = { workspace = true, default-features = false }
kate-recovery = { workspace = true, default-features = false }

# 3rd party
jsonrpsee = { version = "0.20.3", features = ["server", "client", "macros"] }
rayon = { version = "1.5.2" }
moka = { version = "0.12.1", features = ["future"] }


# Substrate
sp-api = { workspace = true, default-features = false }
frame-system = { path = "../../pallets/system", default-features = false }
frame-support = { workspace = true, default-features = false }
sc-client-api = { workspace = true, default-features = false }
sp-blockchain = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }

[features]
default = [ "std" ]
std = [
	"avail-base/std",
	"avail-core/std",
	"da-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"kate-recovery/std",
	"kate/std",
	"sp-api/std",
	"sp-runtime/std",
]

# Enables secure seed generation using for padding fill during the matrix 
# generation for Kate commitment.
# NOTE: WIP because that affects the Data Availability Protocol used during 
# the block import process.
secure_padding_fill = []
