[package]
name = "kate-rpc"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
avail-base = { path = "../../base", default-features = false }
da-runtime = { path = "../../runtime", default-features = false } # check

once_cell = "1.5.2"
sp-api = { version = "4.0.0-dev", default-features = false }
frame-system = { version = "4.0.0-dev" }
sc-client-api = "4.0.0-dev"
sp-blockchain = "4.0.0-dev"
sp-runtime = "7.0.0"

da-primitives = { version = "0.4", default-features = false }
kate = { version = "0.7", default-features = false }

jsonrpsee = { version = "0.16.2", features = ["server", "client", "macros"] }
moka = "0.10"
serde = {version = "1.0", features = ["derive"]}

[features]
default = ["std"]
std = [
	"avail-base/std",
  "kate/parallel",
	"da-runtime/std",
	"sp-api/std",
	"frame-system/std",
	"da-runtime/std",
	"da-primitives/std",
	"kate/std",
	"sp-runtime/std",
]

# Enables secure seed generation using for padding fill during the matrix 
# generation for Kate commitment.
# NOTE: WIP because that affects the Data Availability Protocol used during 
# the block import process.
secure_padding_fill = []
