[package]
name = "mocked-runtime"
version = "1.0.1"
authors = [""]
edition = "2021"
license = "Apache-2.0"
homepage = ""
repository = ""
description = "Mokcked Runtime for Testing"

[dependencies]
avail-core = { workspace = true, default-features = false }
kate = { workspace = true, default-features = false }
da-control = { path = "../dactr" }

scale-info = { version = "2.5.0", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3", features = ["derive"] }
parity-util-mem = { version = "0.12.0", features = ["primitive-types"] }
derive_more = "0.99.17" 
serde = { version = "1.0.195", features = ["derive"] }

frame-support = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
sp-core = { workspace = true, default-features = false }
sp-staking = { workspace = true, default-features = false }
sp-io = { workspace = true, default-features = false }
sp-version = { workspace = true, default-features = false }
sp-inherents = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }

# Pallets
frame-system = { path = "../system" }
pallet-transaction-payment = { path = "../transaction-payment" }
pallet-balances = { workspace = true, default-features = false, features = ["std"] }
pallet-timestamp = { workspace = true, default-features = false }
pallet-babe = { workspace = true, default-features = false }
pallet-staking = { workspace = true, default-features = false }


[features]
default = ["std"]
std = [ ]
try-runtime = []
