[workspace]

[package]
name = "avail-rust"
edition = "2021"
version = "0.1.0"

# Subxt feature dependenices
[target.'cfg(target_arch = "wasm32")'.dependencies]
subxt = { version = "0.37", default-features = false, features = ["web", "jsonrpsee"], optional = true }
subxt-core = { version = "0.37", default-features = false, optional = true  }
subxt-signer = { version = "0.37", default-features = false, features = ["web", "sr25519", "subxt"], optional = true }
avail-core = { git = "https://github.com/availproject/avail-core", tag = "core-node-2", default-features = false, features = ["serde", "runtime", "disable_panic_handler"], optional = true  }
kate-recovery = { git = "https://github.com/availproject/avail-core", tag = "core-node-2", default-features = false, features = ["serde"], optional = true  }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
subxt = { version = "0.37", optional = true  }
subxt-core = { version = "0.37", optional = true  }
subxt-signer = { version = "0.37", optional = true  }
avail-core = { git = "https://github.com/availproject/avail-core", tag = "core-node-2", features = ["serde", "runtime"], optional = true  }
kate-recovery = { git = "https://github.com/availproject/avail-core", tag = "core-node-2", features = ["serde"], optional = true  }


[dependencies]
# Shared dependencies
tokio = { version = "1.21.2", default-features = false }
serde = { version = "1.0.195", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.124", default-features = false, features = ["alloc"] }
hex = { version = "0.4" }

# No-Subxt features dependencies
parity-scale-codec = { version = "3.6.12", default-features = false, optional = true }
blake2b_simd = { version = "1.0.2", default-features = false, optional = true }
jsonrpsee-http-client = { version = "0.24.3", default-features = false, optional = true  }
jsonrpsee-core = { version = "0.24.3", default-features = false, optional = true  }

### Crypto
schnorrkel = { version = "0.11.4", default-features = false, features = ["getrandom"], optional = true }
secrecy = { version = "0.8.0", default-features = false, features = ["alloc"], optional = true  }
regex-lite = { version = "0.1.6", optional = true }
bip39 = { version = "2.0.0", default-features = false, optional = true }
pbkdf2 = { version = "0.12.0", default-features = false, optional = true }
hmac = { version = "0.12.1", optional = true }
sha2 = { version = "0.10.8", default-features = false, optional = true }
ss58-registry = { version = "1.50.0", default-features = false, optional = true  }
bs58 = { version = "0.5.1", default-features = false, features = ["alloc"], optional = true }
blake2 = { version = "0.10.6", default-features = false, optional = true }

# Subxt feature dependenices
derive_more = { version = "0.99.17", optional = true }
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = [
	"derive",
	"full",
	"bit-vec",
], optional = true }
scale-info = { version = "2.5.0", features = ["bit-vec"], optional = true  }
base58 = { version = "0.2.0", optional = true  }
sp-core = { git = "https://github.com/availproject/polkadot-sdk.git", tag = "polkadot-1.7.1-patch-9", default-features = false, optional = true  }
bounded-collections = { version = "0.2.0", features = ["serde"], optional = true  }

[patch.crates-io]
sp-core = { git = "https://github.com/availproject/polkadot-sdk.git", tag = "polkadot-1.7.1-patch-9" }
sp-io = { git = "https://github.com/availproject/polkadot-sdk.git", tag = "polkadot-1.7.1-patch-9" }
sp-runtime = { git = "https://github.com/availproject/polkadot-sdk.git", tag = "polkadot-1.7.1-patch-9" }
sp-std = { git = "https://github.com/availproject/polkadot-sdk.git", tag = "polkadot-1.7.1-patch-9" }

[features]
default = [ "subxt" ]
subxt = [
	"dep:subxt", 
	"subxt-core", 
	"subxt-signer", 
	"avail-core", 
	"kate-recovery", 
	"derive_more", 
	"codec",
	"scale-info",
	"base58",
	"sp-core",
	"bounded-collections",
]
no-subxt = [
	"parity-scale-codec", 
	"blake2b_simd", 
	"jsonrpsee-http-client", 
	"jsonrpsee-core", 
	"schnorrkel",
	"secrecy",
	"regex-lite",
	"bip39",
	"pbkdf2",
	"hmac",
	"sha2",
	"ss58-registry",
	"bs58",
	"blake2",
]
